name: i18n Check (No Hardcoded Strings)

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'app/src/**/*.kt'
      - 'scripts/check_i18n.sh'
      - '.github/workflows/i18n-check.yml'
  push:
    branches: [ main, develop ]
    paths:
      - 'app/src/**/*.kt'
      - 'scripts/check_i18n.sh'

jobs:
  i18n-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x scripts/check_i18n.sh

      - name: Run i18n checker
        run: scripts/check_i18n.sh